### ISSUE TITLE
Map is not pulling update score "colors" even when score "numbers" are correct

### ISSUE THREAD

**Issue by mherrero347** [climatecabinet/scorecard-map#101]
this is an issue originally created by Emma on the main db repo, transferred over here since it's a map issue specifically.

**expected**: MN map should show dark green color for SD-50, since Sen. Melissa Wiklund has a CC Score of 100. 

**current**: The score number is correct, but the map color is wrong. This seems to be true for all districts for which scores were updated on 8.31.21 (also see FL HD-47; Anna Eskamani has a score of 100 which is populating correctly, but the map shows light green instead of dark green).

**steps to reproduce**: Click on map MN --> Senate --> district 50

**Comment by shelbygreen** [comment]
had to refresh the map files (they were about 2 weeks old). now MN SD 50 is showing dark green / properly reflecting it's CC score
