### ISSUE TITLE
Remove the 'Interactive Score Map' title from the the map application.

### ISSUE THREAD

**Issue by mherrero347** [climatecabinet/scorecard-map#104]
**expected behavior**: When viewing the CCA homepage in Webflow, we should see a Webflow-created title for the map module, followed by a small blurb describing how to use the map, and then finally a map iframe. The app inside the iframe should not have a title.

**current behavior**: When viewing the CCA homepage in Webflow, there is no Webflow-created title or blurb, and the map app contains a title reading 'Interactive Score Map,' which should not be there.

**steps to reproduce**: Visit the [test deployment for the homepage](https://www.climatecabinetaction.org/climate-cabinet-action-with-map-test), scroll to the map section.

**fix**: Remove the title from the netlify app, add the title and blurb to the webflow homepage.

**Comment by mcchang** [comment]
@mherrero347 Should I be adding the title and the blurb to the webflow content? What is the blurb I should add?

**Comment by mherrero347** [comment]
> @mherrero347 Should I be adding the title and the blurb to the webflow content? What is the blurb I should add?

Don't worry about that part. Gonna take a stab at that myself and get Caroline/ Emma's thoughts. This pr is plenty, thanks!
