### ISSUE TITLE
vote blurbs only working for 4 states

### ISSUE THREAD

**Issue by shelbygreen** [climatecabinet/scorecard-map#35]
**expected**: vote blurbs should load for every district.

**current**: vote blurbs only load for four states -- AZ, CO, CT, and FL. 

**steps to reproduce**:
1. load the map module
2. select a state outside of the four listed above
3. in the legislator details sidebar, under "selected climate votes", there's no loaded vote blurbs

**Comment by shelbygreen** [comment]
**problem**: the query is only defined for four states -- AZ, CO, CT, and FL -- in the regions.js file. adding additional states raises a query capacity error.

**solution**: 
- remove vote blurbs from the regions.js file. continue to fetch high-level data before map loads
- implement on-demand fetching -- when someone clicks a district, fetch the vote blurbs for that state/chamber/district combination

**Comment by shelbygreen** [comment]
@mcchang -- can you help me this issue? i was able to dynamically generate the vote blurbs, during runtime, but it was by generating pages for each legislator (based on representative._id). that doesn't work because it interferes with the iFrame. any thoughts on how to generate vote blurbs through graphql would be helpful! i was able to implement the id field as a [dynamic variable in the query](https://dgraph.io/docs/graphql/api/variables/), but don't know where/when to declare the value of the dynamic _id string.

**Comment by mcchang** [comment]
@shelbygreen Let me take a look!

**Comment by mcchang** [comment]
@shelbygreen I have a solution, will see if I can throw up a PR today or tomorrow

**Comment by mcchang** [comment]
@shelbygreen I need to clean the PR up a bunch, but I've implemented the fetching in #67.  Essentially I instantiate a graphql client to fetch the vote blurbs. As part of the change, I thought it made sense to make the "legislator page" its own React component and cleaned up a bunch of code
