### ISSUE TITLE
add legislator hyperlink to 'take action' button

### ISSUE THREAD

**Issue by shelbygreen** [climatecabinet/scorecard-map#42]
expected:
- clicking on the 'take action' button will take you to the legislator's page

current:
- clicking on the 'take action' button doesn't do anything

steps to reproduce:
- load the map module
- navigate to a district
- scroll down to the 'take action' button

**Comment by shelbygreen** [comment]
from Matt: 
if you use the following code snippet: `re.sub(r'[^a-z]+', '-', <insert legislator's full name>.lower())` you’ll be able to generate the slug for all legislators except for 27 of them. These legislators have the exact same names as another legislator, and webflow handles it by appending a random hex character to the end of their slug. 

Here’s a list of all the anomalous legislators, their legiscan_id’s, and their webflow slugs:
```
[(21095, 'dave-williams-b'),
 (19137, 'steven-johnson-5'),
 (16545, 'dave-baker-8'),
 (22922, 'david-smith-1'),
 (10405, 'frank-smith-f'),
 (22612, 'charles-miller-5'),
 (2102, 'david-martin-5'),
 (13698, 'chris-brown-9'),
 (11106, 'robert-rodriguez-9'),
 (19405, 'richard-brown-1'),
 (22783, 'brian-stewart-b'),
 (22776, 'mark-johnson-7'),
 (18581, 'david-smith-18'),
 (22046, 'craig-williams-f'),
 (18234, 'jared-solomon-3'),
 (296, 'anthony-deluca-a'),
 (22043, 'brian-smith-4'),
 (21742, 'jerry-carter-5'),
 (21893, 'michael-johnson-8'),
 (11012, 'jim-murphy-c'),
 (5939, 'eddie-lucio-d'),
 (21776, 'david-cook-e'),
 (22522, 'mike-petersen-9'),
 (17744, 'john-bell-f'),
 (13347, 'robert-brooks-1'),
 (22870, 'doug-smith-7'),
 (11206, 'gary-howell-8')]
```

**Comment by mcchang** [comment]
@shelbygreen @mherrero347  I'm happy to take this on along with https://github.com/climatecabinet/scorecard-search/issues/16 if that'd be helpful

**Comment by shelbygreen** [comment]
@mcchang thanks for offering, michael! feel free! the take action button component is in the /map/src/components/Map/Map.js file as 'actionButton' and you will have to edit the /map/src/components/Data/representatives.js file to add the 'slug' field to the query. stuff you probably already know, but wanted to make navigating the files a little easier.
