### ISSUE TITLE
for webflow: put map in a pop-up window on the homepage

### ISSUE THREAD

**Issue by shelbygreen** [climatecabinet/scorecard-map#43]
expected:
- when 'interactive map' is clicked on the homepage, a pop-up window, containing the map, appears

current:
- instead, the user is sent to a new page for the map

steps to reproduce:
- go to the cc scorecard homepage
- click 'interactive map'

**Comment by mherrero347** [comment]
This has been resolved by adding the map directly onto the homepage as it's own section! Closing this issue.
