### ISSUE TITLE
Reset button re-placement

### ISSUE THREAD

**Issue by karanmotwanipro** [climatecabinet/scorecard-map#45]
Hey @shelbygreen 
The title of the map is updated from "Interactive Map" to "Climate Cabinet Scorecard Map" which is making the RESET button conflicting with the title.
Can you please update its location to below the filters on the right? Screenshot attached.
Thank you
<img width="350" alt="Screen Shot 2021-08-13 at 1 20 15 PM" src="https://user-images.githubusercontent.com/85572187/129396582-990e49b6-b2e7-4908-899e-b3bc5d400052.png">

**Comment by shelbygreen** [comment]
@karanmotwanipro, is this still an issue since the title was changed to 'interactive score map', allowing the reset button to maintain its position

**Comment by karanmotwanipro** [comment]
@shelbygreen If we can still move it, it would be great because I want to make the reset button consistent with the search page. Ty

**Comment by karanmotwanipro** [comment]
@shelbygreen
