### ISSUE TITLE
after a district is selected, the options in the district drop-down menu expand to 150

### ISSUE THREAD

**Issue by shelbygreen** [climatecabinet/scorecard-map#56]
**expected behavior**: when a district is selected, only the appropriate number of districts are shown
![Screen Shot 2021-08-16 at 11 37 15 AM](https://user-images.githubusercontent.com/53214352/129590331-f5fa90f1-4bba-488b-a336-5c0ad6938e18.png)

**current behavior**: when a district is selected, the appropriate number of districts are shown. but when the 'district' drop down is selected again, the district number expands to 150.
![Screen Shot 2021-08-16 at 11 29 43 AM](https://user-images.githubusercontent.com/53214352/129590312-8d791493-3896-424e-bdef-e830339dfa9c.png)

**steps to reproduce**:
1. load the map
2. select a state and chamber
3. click a district
4. click the district drop down and scroll down to view the district options

**Comment by mcchang** [comment]
weird, I can't seem to reproduce this @shelbygreen
