### ISSUE TITLE
Distinguish between states with no district data, states with no scores, and districts with no score, and districts with a score of 0

### ISSUE THREAD

**Issue by mcchang** [climatecabinet/scorecard-map#82]
## expected behavior
As a user, I think I would expect the map to distinguish between
1. states with no district data
2. districts in states for which we haven't calculated scores
3. districts in states with an incumbent with "no score" because not enough votes
4. districts in states with an incumbent with a score of 0
## current behavior
- Regions for cases 1, 2, and 3 are all gray.
- Clicking on districts in case 3 and case 4 both result in the sidebar displaying a score of 0.
## steps to reproduce
1. Load the map and click around
Case 3: Siah Correa Hemphill (New Mexico Senate 28)
Case 4: Jennifer Bradley (Florida Senate 5)

## Suggested fix
1. Do not show individual districts for case 2 (i.e. only show the state border)
2. Fix the legislator details for case 3 to show a score of "No Score"

**Comment by shelbygreen** [comment]
map design was updated to only show states included in the initial release
