### ISSUE TITLE
Color coding slightly off in map

### ISSUE THREAD

**Issue by c-spears** [climatecabinet/scorecard-map#97]
**expected behavior**:
When a legislator has a score of 100%, they show up as a dark teal. 
**current behavior**:
Some legislators with 100% scores are showing up with colors in a lower bucket (the 76-99 bucket). This is maybe an issue with rounding one place and not another?
**steps to reproduce**:
Look up Erin Zwiener (Texas HD 42) 
**fix**:

**Comment by shelbygreen** [comment]
had to update the map files, they were about 2 weeks old. now the district colors properly reflect their scores
